#pragma once
typedef const short PKT_TYPE;
PKT_TYPE PKT_TYPE_CS_CHAT_REQ_LOGIN = 1;

PKT_TYPE PKT_TYPE_CS_CHAT_RES_LOGIN = 2;

PKT_TYPE PKT_TYPE_CS_CHAT_REQ_SECTOR_MOVE = 3;

PKT_TYPE PKT_TYPE_CS_CHAT_RES_SECTOR_MOVE = 4;

PKT_TYPE PKT_TYPE_CS_CHAT_REQ_MESSAGE = 5;

PKT_TYPE PKT_TYPE_CS_CHAT_RES_MESSAGE = 6;

PKT_TYPE PKT_TYPE_CS_CHAT_REQ_HEARTBEAT = 7;

